/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.blacksmith.commons.date;

import java.time.LocalDate;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@DisplayName("Date Utils")
public class DateTest {
    @Test
    public void addDaysToDate() {
        assertThat(LocalDateUtils.plusDays(LocalDate.of(2019,01,01),3),is(LocalDate.of(2019,01,04)));
    }
}
